---
layout: cv
title: Brighton Hatch's CV
---
# Brighton Hatch
Software Engineer.

<div id="webaddress">
<a href="mailto:brighton.m.gold@gmail.com">brighton.m.gold@gmail.com</a>
| <a href="https://www.linkedin.com/in/brighton-gold">LinkedIn</a>
| <a href="https://github.com/Brighton-Gold">GitHub</a>
</div>


## Currently

Building software, learning continuously, and turning ideas into working systems.

### Specialized in

Software engineering, application development, quality assurance, and system design.


### Research interests

Programming languages, software architecture, databases, data organization, and game development.


## Education

`Fall 2019 - Fall 2020`
__Southern Virginia University__

- B.A. Computer Science (coursework)

`July 2021 - Present`
__Brigham Young University–Idaho__

- B.A. Software Engineering


## Occupation

`2021 - 2023`
__Liberty Tax Service__, Waynesboro, VA

- Manager
- Receptionist
- Tax Preparer

`Fall 2023 - Winter 2023`
__Brigham Young University–Idaho__, Rexburg, ID

- Teacher’s Assistant, Intro to Programming

`January 2020 - March 2020`
__Von Canon Library__, Buena Vista, VA

- Librarian Receptionist


<!-- ### Footer

Last updated: December 2025 -->
